package gr.dit.hua.entities;
// Generated Dec 29, 2018 12:45:02 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Book", catalog = "books_management")
public class Book implements java.io.Serializable {

	private BookId id;
	private Integer quantity;
	private Integer courseId;
	private Boolean isAvailable;
	private String city;
	private String street;
	private Integer no;

	public Book() {
	}

	public Book(BookId id) {
		this.id = id;
	}

	public Book(BookId id, Integer quantity, Integer courseId, Boolean isAvailable, String city, String street,
			Integer no) {
		this.id = id;
		this.quantity = quantity;
		this.courseId = courseId;
		this.isAvailable = isAvailable;
		this.city = city;
		this.street = street;
		this.no = no;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bookId", column = @Column(name = "bookId", nullable = false)),
			@AttributeOverride(name = "publisherId", column = @Column(name = "publisherId", nullable = false)) })
	public BookId getId() {
		return this.id;
	}

	public void setId(BookId id) {
		this.id = id;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "courseId")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "isAvailable")
	public Boolean getIsAvailable() {
		return this.isAvailable;
	}

	public void setIsAvailable(Boolean isAvailable) {
		this.isAvailable = isAvailable;
	}

	@Column(name = "city", length = 10)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", length = 10)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "no")
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

}
