package gr.dit.hua.entities;
// Generated Dec 29, 2018 12:45:02 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", catalog = "books_management")
public class Course implements java.io.Serializable {

	private int courseId;
	private int professorId;
	private int book1;
	private int book2;
	private String title;

	public Course() {
	}

	public Course(int courseId, int professorId, int book1, int book2, String title) {
		this.courseId = courseId;
		this.professorId = professorId;
		this.book1 = book1;
		this.book2 = book2;
		this.title = title;
	}

	@Id

	@Column(name = "courseId", unique = true, nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Column(name = "professorId", nullable = false)
	public int getProfessorId() {
		return this.professorId;
	}

	public void setProfessorId(int professorId) {
		this.professorId = professorId;
	}

	@Column(name = "book1", nullable = false)
	public int getBook1() {
		return this.book1;
	}

	public void setBook1(int book1) {
		this.book1 = book1;
	}

	@Column(name = "book2", nullable = false)
	public int getBook2() {
		return this.book2;
	}

	public void setBook2(int book2) {
		this.book2 = book2;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}
