package gr.dit.hua.entities;
// Generated Dec 29, 2018 12:45:02 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "State", catalog = "books_management")
public class State implements java.io.Serializable {

	private StateId id;
	private String status;

	public State() {
	}

	public State(StateId id, String status) {
		this.id = id;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "studentId", column = @Column(name = "studentId", nullable = false)),
			@AttributeOverride(name = "courseId", column = @Column(name = "courseId", nullable = false)) })
	public StateId getId() {
		return this.id;
	}

	public void setId(StateId id) {
		this.id = id;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
